services:
  accounts:
    image: "rameshy2415/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - finsafeBank

  loans:
    image: "rameshy2415/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - finsafeBank

  cards:
    image: "rameshy2415/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - finsafeBank


networks:
  finsafeBank:
    driver: bridge