spring:
  application:
    name: gatewayserver
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false  # disabled default behaviour  http://localhost:8072/actuator/gateway/routes
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted

  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayservers"
    description: "Finsafe Bank Gateway server Application"
    version: "1.0.0"

logging:
  level:
    com:
      techinsights:
        gatewayserver: DEBUG

